# Generated by Django 5.0.1 on 2024-01-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0004_keyword"),
        ("rt", "0002_rtsimulation_doi"),
    ]

    operations = [
        migrations.AddField(
            model_name="rtsimulation",
            name="keywords",
            field=models.ManyToManyField(blank=True, to="meta.keyword"),
        ),
    ]
