# Generated by Django 5.0.1 on 2024-04-06 13:46

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rt", "0004_alter_rtsimulation_readme"),
    ]

    operations = [
        migrations.CreateModel(
            name="RTSimulationLightcurveFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(location="/data/rt_data/"), upload_to=""
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="date uploaded")),
                ("description", models.TextField(blank=True)),
                ("is_valid_hesma_file", models.BooleanField(default=False)),
                ("thumbnail", models.ImageField(blank=True, upload_to="")),
                ("interactive_plot", models.JSONField(blank=True, null=True)),
                (
                    "rt_simulation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rt.rtsimulation"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RTSimulationSpectrumFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(location="/data/rt_data/"), upload_to=""
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="date uploaded")),
                ("description", models.TextField(blank=True)),
                ("is_valid_hesma_file", models.BooleanField(default=False)),
                ("thumbnail", models.ImageField(blank=True, upload_to="")),
                ("interactive_plot", models.JSONField(blank=True, null=True)),
                (
                    "rt_simulation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rt.rtsimulation"),
                ),
            ],
        ),
    ]
