# Generated by Django 4.1.9 on 2023-07-19 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQTopic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=300)),
                ("answer", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("topic", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pages.faqtopic")),
            ],
        ),
    ]
