# Generated by Django 5.0.1 on 2024-02-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
