# Generated by Django 4.1.9 on 2023-07-18 02:34

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HydroSimulation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=3000)),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("date", models.DateTimeField(verbose_name="date uploaded")),
                ("author", models.CharField(blank=True, max_length=100)),
                (
                    "readme",
                    models.FileField(
                        blank=True,
                        storage=django.core.files.storage.FileSystemStorage(location="meta_data/"),
                        upload_to="",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
