# Generated by Django 5.0.1 on 2024-01-03 16:25

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("hydro", "0001_initial"),
        ("hydro", "0002_alter_hydrosimulation_author_and_more"),
        ("hydro", "0003_alter_hydrosimulation_name"),
        ("hydro", "0004_alter_hydrosimulation_user"),
        ("hydro", "0005_hydrosimulation_doi"),
        ("hydro", "0006_remove_hydrosimulation_doi"),
        ("hydro", "0007_hydrosimulation_doi"),
    ]

    initial = True

    dependencies = [
        ("meta", "__first__"),
        ("pages", "0002_doi"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HydroSimulation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("reference", models.URLField(blank=True)),
                ("date", models.DateTimeField(verbose_name="date uploaded")),
                ("author", models.CharField(blank=True, max_length=300)),
                (
                    "readme",
                    models.FileField(
                        blank=True,
                        storage=django.core.files.storage.FileSystemStorage(location="meta_data/"),
                        upload_to="",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ("doi", models.ManyToManyField(blank=True, to="meta.doi")),
            ],
        ),
    ]
