# Generated by Django 4.1.9 on 2023-07-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hydro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hydrosimulation",
            name="author",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="hydrosimulation",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="hydrosimulation",
            name="reference",
            field=models.URLField(blank=True),
        ),
    ]
