# Generated by Django 4.1.9 on 2023-07-19 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hydro", "0003_alter_hydrosimulation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hydrosimulation",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
