# Generated by Django 5.0.1 on 2024-01-04 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hydro", "0001_squashed_0007_hydrosimulation_doi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hydrosimulation",
            old_name="doi",
            new_name="DOI",
        ),
    ]
