# Generated by Django 5.0.1 on 2024-01-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hydro", "0008_rename_doi_hydrosimulation_doi"),
        ("meta", "0004_keyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="hydrosimulation",
            name="keywords",
            field=models.ManyToManyField(blank=True, to="meta.keyword"),
        ),
    ]
