# Generated by Django 5.0.1 on 2024-03-03 13:26

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hydro", "0010_alter_hydrosimulation_readme"),
    ]

    operations = [
        migrations.CreateModel(
            name="HydroSimulation1DModelFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(location="/data/hydro_data/"), upload_to=""
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="date uploaded")),
                ("description", models.TextField(blank=True)),
                ("is_valid_hesma_file", models.BooleanField(default=False)),
                (
                    "hydro_simulation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hydro.hydrosimulation"),
                ),
            ],
        ),
    ]
