# Generated by Django 5.0.1 on 2024-03-10 14:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hydro", "0011_hydrosimulation1dmodelfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="hydrosimulation1dmodelfile",
            name="interactive_plot",
            field=models.JSONField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hydrosimulation1dmodelfile",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                storage=django.core.files.storage.FileSystemStorage(location="/data/meta_data/"),
                upload_to="",
            ),
        ),
    ]
