# Generated by Django 5.0.1 on 2024-03-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hydro", "0013_alter_hydrosimulation1dmodelfile_interactive_plot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hydrosimulation1dmodelfile",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
