# Generated by Django 5.0.1 on 2024-02-24 16:33

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracer", "0003_tracersimulation_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracersimulation",
            name="readme",
            field=models.FileField(
                blank=True,
                storage=django.core.files.storage.FileSystemStorage(location="/data/meta_data/"),
                upload_to="",
            ),
        ),
    ]
