# Generated by Django 5.0.1 on 2024-01-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0002_alter_doi_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="doi",
            name="author",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="doi",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doi",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
