# Generated by Django 5.0.1 on 2024-01-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0003_doi_author_doi_date_doi_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("keyword", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
