name: Build docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  pull_request:
    types: [opened, synchronize]

  workflow_dispatch: # manual trigger

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx furo sphinx-copybutton

      - name: Build documentation
        run: |
          cd docs/
          make html
